### PR TITLE
Owen Pull Request

### PR DESCRIPTION
**Pull request by whitleyo**

### CODE REVIEW

**Comment by hyginn** [comment]
Conflicts in testLogTools.R ... did you work from a fork that was not current?

**Comment by whitleyo** [comment]
I did not update the fork as of today.

________________________________

**Comment by hyginn** [comment]
Yes you did.
I resolved it.

**Comment by hyginn** [comment]
So ... where is the check message?

**Comment by whitleyo** [comment]
Good point.


==> devtools::check(document = FALSE)

Setting env vars ---------------------------------------------------------------
CFLAGS  : -Wall -pedantic
CXXFLAGS: -Wall -pedantic
Building rete ------------------------------------------------------------------
"C:/PROGRA~1/R/R-33~1.2/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD build  \
  "C:\Users\HPDM1\Documents\CanadaUofT\4thYear\BCB420\rete" --no-resave-data  \
  --no-manual

* checking for file 'C:\Users\HPDM1\Documents\CanadaUofT\4thYear\BCB420\rete/DESCRIPTION' ... OK
* preparing 'rete':
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* building 'rete_0.1.0.tar.gz'

Setting env vars ---------------------------------------------------------------
_R_CHECK_CRAN_INCOMING_ : FALSE
_R_CHECK_FORCE_SUGGESTS_: FALSE
Checking rete ------------------------------------------------------------------
"C:/PROGRA~1/R/R-33~1.2/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD check  \
  "C:\Users\HPDM1\AppData\Local\Temp\RtmpuqNnZ4/rete_0.1.0.tar.gz" --as-cran  \
  --timings --no-manual

* using log directory 'C:/Users/HPDM1/Documents/CanadaUofT/4thYear/BCB420/rete.Rcheck'
* using R version 3.3.2 (2016-10-31)
* using platform: x86_64-w64-mingw32 (64-bit)
* using session charset: ISO8859-1
* using options '--no-manual --as-cran'
* checking for file 'rete/DESCRIPTION' ... OK
* checking extension type ... Package
* this is package 'rete' version '0.1.0'
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking whether package 'rete' can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking examples ... OK
* checking for unstated dependencies in 'tests' ... OK
* checking tests ...
  Running 'testthat.R' OK
* DONE
Status: OK
 [11s]



R CMD check results
0 errors | 0 warnings | 0 notes

R CMD check succeeded


________________________________

**Comment by hyginn** [comment]
There's an .RData file in the testthat directory which is not loaded in the tests - I assume it's not necessary, right?

**Comment by whitleyo** [comment]
That's a leftover log file I didn't get around to deleting. It's unneccessary. I've commented out the lines that save the data frame (derived from the character vector logVect) so we don't have to deal with an accumulation of these files while we figure out how to merge that information with the global log file.
________________________________

**Comment by hyginn** [comment]
The canonical way is to always use `tempdir()` for testing ...

**Pull request merged**
